### ISSUE TITLE
Cách tách word từ đầu ra của ctc loss paddleocr

### ISSUE THREAD

**Issue by anhalu** [manhdh32/1st_kalapa_ocr#1]
Anh ơi, cho em hỏi xíu ạ, em vừa có xem qua notion của anh ý, em có 1 số thứ hơi thắc mắc ạ. 
- Em thấy a có ghi là sử dụng đầu ra của ctc loss trong paddleocr để anh tính chính xác vị trí của space trong line để anh tạo bộ synthetic data theo mức word (level 2) và chính xác vị trí các từ để tạo level 3, thì trong đoạn code nào anh xử lý việc này ạ. 
- Em có thấy trong tools/gen_synthetic_data.py là động đến gen synthetic data, còn tách từ ctc paddleocr thì em chưa thấy chỗ nào cả ạ.
Em cảm ơn đã bỏ thời gian đọc ạ. @manhdh32

**Comment by manhdh32** [comment]
Hiện tại server của mình bị hẹo nên bị mất code mới nhất của phần đấy rồi, chỉ còn lại một bản cũ b có thể thêm khảo tại tools/auto_split.py (chỉ chứa code cắt từ theo space cho level 2).

Với level 3 (Cắt theo characters) cũng tương tự, có một chút thay đổi là mình train riêng một model với data là ảnh từng word được kéo dãn theo chiều witdh và thực hiện cắt theo ký tự blank thay vì space.
